import { useEffect, useState } from 'react';
import { Radar, RefreshCw } from 'lucide-react';
import { supabase } from '../lib/supabase';

type Row={symbol:string;opportunity?:number;risk?:number;confidence?:number;primary_strategy?:string;consensus_count?:number;market_regime?:string;news_level?:string;veto_active?:boolean;risk_manager_allowed?:boolean;final_action?:string;blocks?:string[];suggested_spend?:number;actual_spend?:number;created_at?:string};

const actionTr:Record<string,string>={BUY:'AL',BUY_CANDIDATE:'ALIM ADAYI',NO_TRADE:'İŞLEM YOK',BLOCKED:'ENGELLENDİ',EXECUTED:'GERÇEKLEŞTİ',NO_DATA:'VERİ YOK'};
const strategyTr:Record<string,string>={SCALP:'Kısa Vade',DAY:'Gün İçi',SWING:'Orta Vade'};

export default function AutoScannerCard(){
  const [rows,setRows]=useState<Row[]>([]);const [loading,setLoading]=useState(false);const [lastRun,setLastRun]=useState<any>(null);
  const load=async()=>{setLoading(true);try{const {data:{user}}=await supabase.auth.getUser();if(!user)return;const [{data:runs},{data:results}]=await Promise.all([supabase.from('autopilot_scan_runs').select('*').eq('user_id',user.id).order('started_at',{ascending:false}).limit(1),supabase.from('autopilot_scan_results').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).limit(50)]);setLastRun(runs?.[0]||null);setRows(results||[])}finally{setLoading(false)}};
  useEffect(()=>{load();const i=setInterval(load,15000);return()=>clearInterval(i)},[]);
  return <div className="bg-zinc-900/50 border border-zinc-800 rounded-xl p-5"><div className="flex items-center justify-between gap-3 mb-4"><div><div className="flex items-center gap-2 text-zinc-100 font-medium"><Radar size={18} className="text-cyan-400"/> Otomatik Piyasa Tarayıcısı • Supabase</div><p className="text-xs text-zinc-500 mt-1">7/24 bulut tarayıcısı her dakika çalışır; Top 50 USDT piyasasını dönüşümlü tarar, uygun sanal işlemleri otomatik açar ve kaydeder.</p></div><button title="Yenile" onClick={load} className="p-2 rounded-lg bg-zinc-800 text-zinc-300"><RefreshCw size={15} className={loading?'animate-spin':''}/></button></div>
  <div className="grid grid-cols-2 md:grid-cols-5 gap-2 mb-4 text-xs"><Metric label="Taranan" value={String(lastRun?.scanned_count??0)}/><Metric label="Aday" value={String(lastRun?.candidate_count??0)}/><Metric label="Risk Onaylı" value={String(lastRun?.risk_allowed_count??0)}/><Metric label="Gerçekleşen" value={String(lastRun?.executed_count??0)}/><Metric label="Engellenen" value={String(lastRun?.blocked_count??0)}/></div>
  <div className="space-y-2 max-h-80 overflow-y-auto">{rows.length===0?<div className="text-xs text-amber-300 bg-amber-500/5 border border-amber-500/20 rounded-lg p-3">Henüz tarama sonucu yok. İlk otomatik tarama en geç yaklaşık 1 dakika içinde burada görünür.</div>:rows.map((r,i)=><div key={`${r.symbol}-${i}`} className="grid grid-cols-[70px_1fr_auto] gap-3 rounded-lg border border-zinc-800 bg-zinc-950/60 p-3 text-xs"><b>{r.symbol}</b><div className="text-zinc-400">Fırsat {r.opportunity??'-'} • Risk {r.risk??'-'} • Güven {r.confidence??'-'} • {strategyTr[r.primary_strategy||'']||r.primary_strategy||'-'}<div className="text-zinc-600 mt-1">{Array.isArray(r.blocks)?r.blocks.join(' • '):''}</div></div><span className="text-amber-400">{actionTr[r.final_action||'NO_DATA']||r.final_action}</span></div>)}</div></div>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="bg-zinc-950/60 rounded-lg p-2 border border-zinc-800"><div className="text-zinc-500">{label}</div><div className="text-zinc-200 font-semibold mt-1">{value}</div></div>}
