import { useEffect, useMemo, useState } from 'react';
import { FlaskConical, RefreshCw, TriangleAlert, ShieldCheck } from 'lucide-react';
import { supabase } from '../lib/supabase';

type Shadow={status:string;return_pct:number|null;decision_with_news:string|null;decision_without_news:string|null;news_contribution_usd:number|null;news_cost_usd:number|null;ai_cost_usd:number|null;horizon_minutes:number|null};
export default function ResearchLabCard(){
  const [shadow,setShadow]=useState<Shadow[]>([]);const [backtests,setBacktests]=useState<any[]>([]);const [loading,setLoading]=useState(false);
  const load=async()=>{setLoading(true);try{const {data:{user}}=await supabase.auth.getUser();if(!user)return;const [{data:s},{data:b}]=await Promise.all([supabase.from('shadow_signals').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).limit(2000),supabase.from('backtest_runs').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).limit(10)]);setShadow(s||[]);setBacktests(b||[])}finally{setLoading(false)}};
  useEffect(()=>{load();const i=setInterval(load,30000);return()=>clearInterval(i)},[]);
  const stats=useMemo(()=>{const resolved=shadow.filter(x=>x.status==='RESOLVED'&&(x.horizon_minutes||0)>=15),open=shadow.filter(x=>x.status==='OPEN');const diff=resolved.filter(x=>x.decision_with_news!==x.decision_without_news);const contribution=resolved.reduce((s,x)=>s+Number(x.news_contribution_usd||0),0);const costs=resolved.reduce((s,x)=>s+Number(x.news_cost_usd||0)+Number(x.ai_cost_usd||0),0);return{resolved:resolved.length,open:open.length,diff:diff.length,contribution,costs,enough:resolved.length>=50}},[shadow]);
  const latest=backtests[0];const metrics=latest?.metrics||{};
  return <div className="bg-zinc-900/50 border border-zinc-800 rounded-xl p-5"><div className="flex items-center justify-between mb-4"><div><div className="flex items-center gap-2 text-zinc-100 font-medium"><FlaskConical size={18} className="text-violet-400"/> Validation Lab • Supabase</div><p className="text-xs text-zinc-500 mt-1">Shadow ve backtest kayıtları artık Supabase PostgreSQL'den okunur.</p></div><button onClick={load} className="p-2 rounded-lg bg-zinc-800 text-zinc-300"><RefreshCw size={15} className={loading?'animate-spin':''}/></button></div>
  <div className="grid grid-cols-2 md:grid-cols-4 gap-3 text-sm mb-4"><Metric label="Çözülmüş Shadow" value={String(stats.resolved)}/><Metric label="Bekleyen Shadow" value={String(stats.open)}/><Metric label="Haber Kararı Değiştirdi" value={String(stats.diff)}/><Metric label="Net Haber Katkısı" value={`${stats.contribution>=0?'+':''}$${stats.contribution.toFixed(2)}`}/></div>
  <div className={`rounded-lg border p-4 mb-4 ${stats.enough?'border-emerald-500/20 bg-emerald-500/5':'border-amber-500/20 bg-amber-500/5'}`}><div className="flex items-center gap-2 text-sm font-medium">{stats.enough?<ShieldCheck size={17} className="text-emerald-400"/>:<TriangleAlert size={17} className="text-amber-400"/>} CryptoPanic / Haber Motoru Retest</div><p className="text-xs mt-2 text-zinc-400">Geçerli örnek: {stats.resolved}/50 • News + AI maliyeti: ${stats.costs.toFixed(2)}. En az 50 adet 15+ dakikalık çözülmüş shadow olmadan kalıcı karar yok.</p></div>
  {latest?<div className="bg-zinc-950/60 border border-zinc-800 rounded-lg p-4"><div className="text-xs text-zinc-500 mb-2">Son Supabase Backtest Kaydı</div><div className="grid grid-cols-2 md:grid-cols-4 gap-2 text-xs"><Metric label="Tip" value={String(latest.run_type||'-')}/><Metric label="İşlem" value={String(metrics.trades??'-')}/><Metric label="Net Getiri" value={metrics.netReturnPct!=null?`%${metrics.netReturnPct}`:'-'}/><Metric label="Max DD" value={metrics.maxDrawdownPct!=null?`%${metrics.maxDrawdownPct}`:'-'}/></div></div>:<div className="text-xs text-zinc-500 bg-zinc-950/60 border border-zinc-800 rounded-lg p-3">Cloud backtest runner henüz deploy edilmedi. Önce veri/auth geçişini doğruluyoruz.</div>}
  </div>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="bg-zinc-950/60 rounded-lg p-2 border border-zinc-800/70"><div className="text-zinc-500">{label}</div><div className="font-medium text-zinc-200 mt-1 break-words">{value}</div></div>}
