import { X, Settings2, Shield, Database, RotateCcw } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { resetPaper100 } from '../lib/cloudData';

export default function SettingsModal({isOpen,onClose}:{isOpen:boolean;onClose:()=>void}){
  const {state,setDailyTarget,setPositionSizePercent,setRiskSettings}=useApp();
  if(!isOpen)return null;
  const reset=async()=>{if(!confirm('Supabase PAPER100 portföyü, işlem geçmişi ve sinyaller silinip bakiye 100 USDT olarak sıfırlansın mı?'))return;try{await resetPaper100();window.location.reload()}catch(e:any){alert(e?.message||'Reset başarısız')}};
  return <div className="fixed inset-0 z-50 bg-black/75 backdrop-blur-sm flex justify-end"><div className="w-full max-w-lg h-full bg-zinc-950 border-l border-zinc-800 overflow-y-auto"><div className="p-5 border-b border-zinc-800 flex justify-between items-center"><h2 className="text-lg font-medium flex items-center gap-2"><Settings2 size={18}/>Supabase PAPER100 Ayarları</h2><button onClick={onClose}><X size={20}/></button></div><div className="p-5 space-y-6">
    <section><h3 className="text-sm uppercase tracking-wider text-zinc-400 flex items-center gap-2 mb-4"><Shield size={15}/>Risk ve sermaye</h3><div className="space-y-5"><Range label="Pozisyon başına maksimum sermaye" value={state.positionSizePercent} min={5} max={50} step={5} suffix="%" onChange={setPositionSizePercent}/><Range label="İşlem başına risk" value={state.riskPerTradePercent} min={0.1} max={2} step={0.1} suffix="%" onChange={v=>setRiskSettings({riskPerTradePercent:v})}/><Range label="Maksimum toplam açık risk" value={state.maxOpenRiskPercent} min={0.5} max={8} step={0.25} suffix="%" onChange={v=>setRiskSettings({maxOpenRiskPercent:v})}/><Range label="Günlük zarar limiti" value={state.maxDailyLossPercent} min={0.5} max={8} step={0.5} suffix="%" onChange={v=>setRiskSettings({maxDailyLossPercent:v})}/><Range label="Günlük referans kâr bölgesi" value={state.dailyTargetPercent} min={1} max={10} step={0.5} suffix="%" onChange={setDailyTarget}/><Range label="Maksimum açık pozisyon" value={state.maxPositions} min={1} max={8} step={1} suffix="" onChange={v=>setRiskSettings({maxPositions:v})}/></div></section>
    <section className="border-t border-zinc-800 pt-5"><h3 className="text-sm uppercase tracking-wider text-zinc-400 flex items-center gap-2 mb-3"><Database size={15}/>Cloud mimarisi</h3><div className="bg-blue-500/10 border border-blue-500/20 rounded-lg p-3 text-xs text-blue-300/80">Auth + PAPER100 hesap/pozisyon/ayar/sinyal verileri Supabase'de. Binance public fiyatları anahtarsız alınır. Gerçek emir API'si bu cloud geçiş paketinde yoktur.</div><button onClick={reset} className="mt-3 w-full p-3 rounded-lg border border-amber-500/30 bg-amber-500/10 text-amber-300 text-sm flex items-center justify-center gap-2"><RotateCcw size={16}/>100 USDT Testini Sıfırla</button></section>
  </div></div></div>;
}
function Range({label,value,min,max,step,suffix,onChange}:{label:string;value:number;min:number;max:number;step:number;suffix:string;onChange:(v:number)=>void}){return <div><div className="flex justify-between text-sm mb-2"><span className="text-zinc-300">{label}</span><b className="text-emerald-400">{value}{suffix}</b></div><input type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))} className="w-full accent-emerald-500"/></div>}
