import { useEffect, useMemo, useState } from 'react';
import { useApp } from '../context/AppContext';
import { formatCurrency, cn } from '../lib/utils';
import { X, TrendingUp, TrendingDown, Activity, ShieldCheck } from 'lucide-react';
import { ResponsiveContainer, AreaChart, Area, XAxis, YAxis, Tooltip } from 'recharts';
import { fetchKlines } from '../lib/binancePublic';

export default function TradeModal(){
  const {tradingModal,closeTradeModal,executeManualTrade,state}=useApp();
  const [tradeType,setTradeType]=useState<'BUY'|'SELL'>('BUY');
  const [amountUSD,setAmountUSD]=useState('');
  const [chartData,setChartData]=useState<any[]>([]);
  const coin=tradingModal.coin;
  const cap=useMemo(()=>Math.max(0,state.balance*((state.positionSizePercent||25)/100)),[state.balance,state.positionSizePercent]);
  useEffect(()=>{if(!coin)return;setAmountUSD(String(Math.max(0,Math.min(cap,state.balance)).toFixed(2)));fetchKlines(coin.symbol,'1h',48).then(d=>setChartData(d.map(x=>({time:new Date(x.time).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),price:x.close})))).catch(()=>setChartData([]))},[coin?.symbol,cap,state.balance]);
  if(!tradingModal.isOpen||!coin)return null;
  const amount=Number(amountUSD)||0,isPositive=coin.change24h>=0;
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-4"><div className="bg-zinc-950 border border-zinc-800 w-full max-w-5xl rounded-2xl overflow-hidden flex flex-col md:flex-row max-h-[95vh]">
    <div className="flex-1 border-b md:border-b-0 md:border-r border-zinc-800 overflow-y-auto"><div className="p-6 border-b border-zinc-800 flex justify-between"><div><h2 className="text-xl font-bold text-zinc-100">{coin.symbol}/USDT</h2><span className="text-sm text-zinc-500">Binance Spot • public canlı veri • PAPER100</span></div><div className="text-right"><div className="text-2xl font-bold">{formatCurrency(coin.price)}</div><div className={cn('text-sm',isPositive?'text-emerald-400':'text-rose-400')}>{isPositive?<TrendingUp size={16} className="inline"/>:<TrendingDown size={16} className="inline"/>} {coin.change24h.toFixed(2)}%</div></div></div>
    <div className="p-6 min-h-[300px]"><h3 className="text-sm text-zinc-400 flex gap-2 mb-4"><Activity size={16}/>48 Saatlik Gerçek Mum Kapanışları</h3><div className="h-56"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><XAxis dataKey="time" hide/><YAxis domain={['auto','auto']} hide/><Tooltip formatter={(v:number)=>[formatCurrency(v),'Fiyat']}/><Area type="monotone" dataKey="price" stroke="#10b981" fillOpacity={0.12} fill="#10b981"/></AreaChart></ResponsiveContainer></div></div>
    <div className="px-6 pb-6"><div className="border border-emerald-500/20 bg-emerald-500/5 rounded-xl p-4"><div className="flex items-center gap-2 font-medium mb-2"><ShieldCheck className="text-emerald-400" size={18}/> Supabase Paper Guard</div><div className="grid grid-cols-2 md:grid-cols-4 gap-3 text-xs"><Metric label="Serbest Bakiye" value={`${state.balance.toFixed(2)} USDT`}/><Metric label="Pozisyon Limiti" value={`%${state.positionSizePercent}`}/><Metric label="Bu İşlem Üst Sınırı" value={`${cap.toFixed(2)} USDT`}/><Metric label="Gerçek Emir" value="KAPALI"/></div><p className="text-xs text-zinc-500 mt-3">Bu cloud geçiş sürümünde manuel PAPER işlem Supabase RPC ile atomik kaydedilir. Strategy/Risk/News otomatik motoru Edge Function aşamasında taşınacak.</p></div></div></div>
    <div className="w-full md:w-96 bg-zinc-900/50 overflow-y-auto"><div className="p-4 border-b border-zinc-800 flex justify-between"><h3 className="font-medium">Supabase PAPER100</h3><button onClick={closeTradeModal}><X size={18}/></button></div><div className="p-6 space-y-5"><div className="flex rounded-lg bg-zinc-950 p-1 border border-zinc-800"><button onClick={()=>setTradeType('BUY')} className={cn('flex-1 py-2 rounded-md',tradeType==='BUY'?'bg-emerald-500/20 text-emerald-400':'text-zinc-500')}>AL</button><button onClick={()=>setTradeType('SELL')} className={cn('flex-1 py-2 rounded-md',tradeType==='SELL'?'bg-rose-500/20 text-rose-400':'text-zinc-500')}>POZİSYONU SAT</button></div>{tradeType==='BUY'&&<div><label className="text-xs text-zinc-400">Tutar (USDT)</label><input type="number" min="0" max={cap} step="0.01" value={amountUSD} onChange={e=>setAmountUSD(e.target.value)} className="mt-2 w-full bg-zinc-950 border border-zinc-800 rounded-lg p-3"/><p className="text-xs text-zinc-500 mt-2">Supabase RPC, pozisyon yüzdesi ve mevcut bakiye limitini tekrar doğrular.</p></div>}</div><div className="p-6 border-t border-zinc-800"><button disabled={tradeType==='BUY'&&(amount<=0||amount>cap)} onClick={()=>executeManualTrade(tradeType,coin.symbol,amount)} className={cn('w-full py-4 rounded-xl font-bold disabled:opacity-40',tradeType==='BUY'?'bg-emerald-500':'bg-rose-500')}>{tradeType==='BUY'?'Sanal Spot Alış':'Açık Pozisyonu Sat'}</button></div></div>
  </div></div>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="bg-zinc-950/60 rounded-lg p-2"><div className="text-zinc-500">{label}</div><div className="font-medium text-zinc-200 mt-1">{value}</div></div>}
